### ISSUE TITLE
Allow specifying the exact `tsconfig` file we want `tstyche` to use, not just the nearest named `tsconfig.json`

### ISSUE THREAD

**Issue by ekilah** [tstyche/tstyche#308]
The docs say

> To load the compiler options for a test file, TSTyche searches for the nearest tsconfig.json which includes the file in question

It appears that this search does not include looking for files named something like `tsconfig.foobar.json`, or in my case, `tsconfig.typetest.ts`, that may include our test files.

Our project has multiple `tsconfig` files, where we have one base config named `tsconfig.base.json` that most other files extend. When we use a tool that requires its own `tsconfig`, we will make a new one that `extends` `tsconfig.base.json`, like `tsconfig.jest.json` or `tsconfig.eslint.json`. This way, we can customize which files to `include` or `exclude` for that tool, while sharing a "base" config for all of the tools.

Our project's file named `tsconfig.json` exists only for tools and things like IDEs that don't allow specifying a specific `tsconfig`, and that file ends up including almost everything (so things like IDE hints work in every file, whether it is a test file or a real part of our application).

The reason I want this is:

- We colocate our type test files alongside the file it is testing types from (i.e. we don't have a `src/__typetest__/` file for all of our type tests)
- the few type tests we have run _significantly_ faster (2 seconds vs 12 seconds) if we move  them to a single `src/__typetest__/` folder, because that's the only way we can specify a special `tsconfig` (named `tsconfig.json`) just for these tests. Presumably this speedup is because there are way fewer files for the tool to scan over (thanks to the custom `tsconfig`'s `include` directive).

If I could tell `tstyche` to use `tsconfig.tstyche.json`, or `tsconfig.typetests.json`, or whatever, then I could get the speed benefits without colocating the files, which is what I'd prefer.

**Comment by mrazauskas** [comment]
Thanks for reminder. This is a nice to have feature, but having it requires reimplementing project service. I will do this at some point, because that is useful for other parts of TSTyche. But that will take time.

By the way, did you try using `references` as documented here: https://tstyche.org/guide/typescript-project#next-to-source-files. Exclude type test files from the root `tsconfig.json` and add a reference to `tsconfig.typetests.json` that includes these files. This should work for IDEs and with TSTyche.

Is there any reason you cannot use `references`?

---

TSTyche is retrieving type information via project service (a wrapper around language service), which is the same API used by your IDE. This means that, performance improvement must be notable in both TSTyche and code editors. The main difference is that: TSTyche creates language service with each run; code editors create it once and it runs in watch mode. So the performance penalty is less visible.

Another slow part of TSTyche: it has to walk the whole file tree to select test files. In a large project a pattern like `"**/*.tst.*"` is much slower than `"src/*.tst.*"`. Probably I should add this to documentation.

**Comment by mrazauskas** [comment]
Do I get it right that you are using `ts-jest` and `typescript-eslint`? It is interesting how and why other tools are consuming provided TSConfig files.

For instance, `ts-jest` is only reading `compilerOptions`. Looks like the rest is ignored. And for good reason, because `includes` or `references` can slow down type checking. In the other hand, ignoring `references` makes it less correct. They could use project/language service, which works on per file basis instead of per program. All fields of TSConfig would be respected without performance penalty.

This is more or less the reason why `typescript-eslint` was recently putting efforts to wrap around TypeScript's project service. Seems like in their case providing a custom TSConfig is in the past. From their [documentation](https://typescript-eslint.io/getting-started/typed-linting#can-i-customize-the-tsconfig-used-for-typed-linting):

> Can I customize the TSConfig used for typed linting?
> Yes, but it's not recommended in most configurations. [...]

---

For me it seems that wrapping around project/language service is the future of type checking tools.

Build tools is a different story. I see why `tsc --project tsconfig.prod.json` makes sense. But I think that the output of a type checking tool must be in sync with the output of a code editor. In most situations that’s the best thing. (Of course, providing a custom `tsconfig.json` can be helpful in some rare cases, so TSTyche will have that option in the future.)

**Comment by mrazauskas** [comment]
The `tsconfig` option shipped with `tstyche@3.0.0-beta.5`. Give it a try. I plan to publish RC release in a couple of weeks.

Usage is documented in the Release Notes: https://tstyche.org/releases/tstyche-3#configuration

---

By the way, although a custom TSConfig is required to include all test files, I don’t think `include` / `exclude` can influence the performance. Because language service and compiler work differently. The compiler (`tsc`) treats included files as entry points, but the service responds to queries on per file bases. TSTyche is asking for diagnostics for each test file. Hence only these test files are the entry points (instead of all included files).

The `types` field is a different story. Keeping the list minimal (or event setting `"types": []`) would most definitely improve the performance. Because any `@types/*` library can declare variable in the global scope, they all must be analysed by the compiler.

**Comment by mrazauskas** [comment]
Shipped with [tstyche@3.0.0](https://github.com/tstyche/tstyche/releases/tag/v3.0.0).

**Comment by ekilah** [comment]
Thank you, sorry for the late reply.

We've recently been changing our `tsconfig` for other reasons (actually moving to having a single one again 😂) since my report here, so I haven't been able to verify this, but I appreciate it regardless
